env: "local"
server:
  host: "localhost"
  port: 8000
  timeout: 5s
  idle_timeout: 60s
  shutdown_timeout: 5s
postgres:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "rootroot"
  database: "service-courier"
  maxConns: 20
  minConns: 5
  maxConnLifetime: 1h
  maxConnIdleTime: 30m
  healthCheckPeriod: 60s